CREATE TABLE "dsjzx"."zjw_wgh_t_contactinfo_23" (
    "URGENTDEGREE" character varying(100 char) NULL,
	"JHPT_UPDATE_TIME" timestamp(6) without time zone NULL,
	"CREATENOTE" text NULL,
	"SOLVINGRESULT_JZ" text NULL,
	"ISEND" character varying(100 char) NULL,
	"LONGITUDE_WGS84" numeric(22,0) NULL,
	"SOLVINGRESULT_F" text NULL,
	"SOLVINGTIME" timestamp(6) without time zone NULL,
	"INFOSOURCENAME" character varying(500 char) NULL,
	"INFOSCCODE" character varying(100 char) NULL,
	"AREACODE" character varying(100 char) NULL,
	"LASTSOLVINGTIME_JZ" timestamp(6) without time zone NULL,
	"SOLVINGNOTE_F" text NULL,
	"DISPATCHNOTE_LAFP" text NULL,
	"DISPATCHTIME" timestamp(6) without time zone NULL,
	"ADDRESS" text NULL,
	"DEPTNAME" character varying(100 char) NULL,
	"SOLVINGTIME_LAFP" timestamp(6) without time zone NULL,
	"DISPATCHUSER_JZ" character varying(100 char) NULL,
	"STREETNAME" character varying(100 char) NULL,
	"BANLIRESULT" text NULL,
	"CHECKDELAYTIME_SJ" timestamp(6) without time zone NULL,
	"ACCEPTDEPTCODE_L" character varying(100 char) NULL,
	"NOWSTATUSNAME" character varying(20 char) NULL,
	"SOLVINGRESULT_LAFP" text NULL,
	"ACCEPTDEPTCODE_JZ" character varying(100 char) NULL,
	"LASTSOLVINGTIME_L" timestamp(6) without time zone NULL,
	"DISPATCHDEPTCODE_JZ" character varying(100 char) NULL,
	"ACCEPTTIME_F" timestamp(6) without time zone NULL,
	"DISPATCHTIME_LAFP" timestamp(6) without time zone NULL,
	"VERIFYRESULT" character varying(100 char) NULL,
	"DISPATCHTIME_JZ" timestamp(6) without time zone NULL,
	"NOEWTRACKOPETIME" timestamp(6) without time zone NULL,
	"ENDNOTE" text NULL,
	"DELAYNOTE_SJ" text NULL,
	"INFOTYPENAME" character varying(500 char) NULL,
	"SOLVINGRESULT_L" character varying(100 char) NULL,
	"SOLVINGTIME_L" timestamp(6) without time zone NULL,
	"SOLVINGTIME_JZ" timestamp(6) without time zone NULL,
	"RELATED_TASKID" character varying(500 char) NULL,
	"INSERTTIME" timestamp(6) without time zone NULL,
	"PARTSN" character varying(500 char) NULL,
	"DISPATCHDEPTCODE_L" character varying(100 char) NULL,
	"SHANGBAOHESHITIME" timestamp(6) without time zone NULL,
	"CANCLETIME" timestamp(6) without time zone NULL,
	"INFOBCNAME" character varying(500 char) NULL,
	"ACCEPTTIME_L" timestamp(6) without time zone NULL,
	"LASTSOLVINGTIME_F" timestamp(6) without time zone NULL,
	"TASKID" character varying(100 char) NULL,
	"INFOSCNAME" character varying(500 char) NULL,
	"CHECKDEPTBACKTIME_SJ" timestamp(6) without time zone NULL,
	"LATITUDE_WGS84" numeric(22,0) NULL,
	"BUSINESS_TIME" timestamp(6) without time zone NULL,
	"INFOBCCODE" character varying(100 char) NULL,
	"ALLENDTIME" timestamp(6) without time zone NULL,
	"DISPATCHUSER_F" character varying(100 char) NULL,
	"ID" numeric(22,0) NULL,
	"SOLVINGTIME_F" timestamp(6) without time zone NULL,
	"DISPATCHDEPTCODE_LAFP" character varying(100 char) NULL,
	"COMMUNITYCODE" character varying(100 char) NULL,
	"ACCEPTDEPTCODE_F" character varying(100 char) NULL,
	"DEPTCODE" character varying(100 char) NULL,
	"DISPATCHTIME_F" timestamp(6) without time zone NULL,
	"DISPATCHUSER_LAFP" character varying(100 char) NULL,
	"TUID" character varying(100 char) NULL,
	"DISPATCHDEPTCODE_F" character varying(100 char) NULL,
	"ISOVERDUE" character varying(100 char) NULL,
	"GRIDCODE" character varying(100 char) NULL,
	"INFOZCNAME" character varying(100 char) NULL,
	"COMMUNITYNAME" character varying(100 char) NULL,
	"DISPATCHNOTE_JZ" text NULL,
	"NEWWORKGRIDCODE" character varying(100 char) NULL,
	"ACCEPTDEPTCODE" character varying(100 char) NULL,
	"BACKDEPTCODE_SJ" character varying(100 char) NULL,
	"CHECKRESULT" text NULL,
	"HESHI" character varying(100 char) NULL,
	"SHANGBAOHECHATIME" timestamp(6) without time zone NULL,
	"DISPATCHUSER" character varying(100 char) NULL,
	"DISPATCHNOTE_L" text NULL,
	"SOLVINGNOTE_L" text NULL,
	"DISPATCHDEPTCODE" character varying(100 char) NULL,
	"DISCOVERTIME" timestamp(6) without time zone NULL,
	"BACKNOTE" text NULL,
	"SOLVINGNOTE" text NULL,
	"INFOZCCODE" character varying(100 char) NULL,
	"DELAYDEPTCODE" character varying(100 char) NULL,
	"CREATETIME" timestamp(6) without time zone NULL,
	"REPORTER" character varying(100 char) NULL,
	"BACKDEPTCODE" character varying(100 char) NULL,
	"SOLVINGRESULT" text NULL,
	"CASEEND" character varying(100 char) NULL,
	"NOWTRACKCODE" character varying(200 char) NULL,
	"STREETCODE" character varying(100 char) NULL,
	"ISCREATE" character varying(100 char) NULL,
	"BACKNOTE_SJ" text NULL,
	"CHECKDELAYTIME" timestamp(6) without time zone NULL,
	"ISSTANDARD" character varying(20 char) NULL,
	"DISPATCHUSER_L" character varying(100 char) NULL,
	"LASTSOLVINGTIME" timestamp(6) without time zone NULL,
	"ACCEPTDEPTCODE_LAFP" character varying(100 char) NULL,
	"DELAYNOTE" text NULL,
	"COORDY" numeric(22,0) NULL,
	"LASTSOLVINGTIME_LAFP" timestamp(6) without time zone NULL,
	"JHPT_DELETE" character(10 char) NULL,
	"SYNCTIME" timestamp(6) without time zone NULL,
	"CHECKDEPTBACKTIME" timestamp(6) without time zone NULL,
	"SOLVINGNOTE_LAFP" text NULL,
	"YEAR" character varying(4 char) NULL,
	"SOLVINGNOTE_JZ" text NULL,
	"DELAYDEPTCODE_SJ" character varying(100 char) NULL,
	"DISPATCHTIME_L" timestamp(6) without time zone NULL,
	"ACCEPTTIME_JZ" timestamp(6) without time zone NULL,
	"ISCANCEL" character varying(100 char) NULL,
	"INFOSOURCEID" character varying(100 char) NULL,
	"NOWTRACKNAME" character varying(100 char) NULL,
	"INFOTYPEID" character varying(100 char) NULL,
	"ACCEPTTIME_LAFP" timestamp(6) without time zone NULL,
	"COORDX" numeric(22,0) NULL,
	"NOWSTATUS" character varying(20 char) NULL,
	"CONTACTINFO" character varying(100 char) NULL,
	"ACCEPTTIME" timestamp(6) without time zone NULL,
	"CANCELNOTE" text NULL,
	"HECHA" character varying(100 char) NULL,
	"ALLTIME" numeric(22,0) NULL,
	"DISPATCHNOTE" text NULL,
	"DISPATCHNOTE_F" text NULL,
	"AREANAME" character varying(50 char) NULL,
	"DESCRIPTION" text NULL,
	"ISDELAY" character varying(100 char) NULL,
	"ENDTIME" timestamp(6) without time zone NULL,
	"ISRETURN" character varying(100 char) NULL,
	"DSJZX_TASKID" character varying(10 char) NULL,
	"grid_code" character varying(255 char) NULL,
	"grid_name" character varying(255 char) NULL,
	"county" character varying(255 char) NULL,
	"town" character varying(255 char) NULL,
	"point_x" numeric(38,8) NULL,
	"point_y" numeric(38,8) NULL,
	"area" text NULL,
	"area_code" text NULL,
	"street" text NULL,
	"street_code" text NULL,
	"discovertime_ts" timestamp(6) without time zone NULL,
	"discover_time_ts" text NULL,
	"ymd" text NULL,
	"discover_time_ym" text NULL,
	"MARK_UUID" character varying(100 char) NOT NULL,
	"MARK_BUSINESS_TIME" timestamp(6) without time zone NULL,
	"MARK_RKBS" character varying(100 char) NULL,
	"MARK_UPDATE_TIME" timestamp(6) without time zone NULL,
	"MARK_DATA_STATUS" character varying(100 char) NULL,
	"MARK_FLAG" character varying(10 char) NULL,
	"MARK_ERROR_INFO" text NULL,
	"MARK_EXCHANGE_TIME" timestamp(6) without time zone NULL,
	"MARK_FINISH_DATE" timestamp(6) without time zone NULL,
	"inc_id" integer AUTO_INCREMENT,
	CONSTRAINT "zjw_wgh_aj_zxx_0404_test_pkey" PRIMARY KEY (MARK_UUID)
);